config/routes.rb
Ineed::Application.routes.draw do
  get "vendors/dashboard"
  get "users/dashboard"
  devise_for :users, :controllers => {:registrations => "users/registrations"}

  devise_scope :user do
    get "registrations/:role", to: "users/registrations#new", as: :registrations_by_role
  end

  match 'users/dashboard' => 'users#dashboard', :via => :get, :as => :user_dashboard
  match 'vendors/dashboard' => 'vendors#dashboard', :via => :get, :as => :vendor_dashboard
  get "home/index"

  namespace :vendors do
    resources :products
  end

  resources :products

  root 'home#index'
  ActiveAdmin.routes(self)

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :categorizations
  has_many :categories, :through => :categorizations
  belongs_to :user

  def added_categories
    self.categories.map(&:name).join(",")
  end

  def to_s
    "#{self.name}"
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name,:description,:price, :categories)
    end
end

app/controllers/vendors/products_controller.rb
class Vendors::ProductsController < ApplicationController
  before_action :authenticate_vendor!
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = current_user.products
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to vendors_products_path(@product), notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to vendors_products_path(@product), notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to vendors_products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name,:description,:price, :category_ids => [])
    end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :authenticate_user!
  def dashboard
  end
end

app/helpers/products_helper.rb
module ProductsHelper

  def price_display(price)
    return "N/A" if price.blank?
    price
  end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/products/_form.html.erb
<% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

    <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= simple_form_for([:vendors,@product],html: {class: 'form-horizontal' }) do |f| %>
  <div class="form-inputs">
    <%= f.input :name, input_html: { class: 'form-control' } %>
    <%= f.input :description, input_html: { class: 'form-control' } %>
    <%= f.input :price, input_html: { class: 'form-control' } %>
    <%= f.association :categories, collection: Category.viewable_categories.all(order: 'name'), prompt: "Choose some categories",input_html: { class: 'form-control chosen-select' } %>
    <%#= f.association :categories,input_html: { class: 'form-control chosen-select' } %>
  </div>


  <div class="actions">
    <%= f.button :submit %>
    <%#= f.button :next %>
  </div>
<% end %>

app/views/vendors/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<br>
<%= link_to 'Show', vendors_product_path(@product) %> |
<%= link_to 'Back', vendors_products_path %>

app/views/vendors/products/index.html.erb
<div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-10 col-md-offset-1">
        <%= link_to 'New Product', new_vendors_product_path %>
        <h1>Listing products</h1>
          <table class="table table-hover">
              <thead>
                  <tr>
                      <th>Products with Description</th>
                      <th class="text-center">Price</th>
                      <th> </th>
                  </tr>
              </thead>
              <tbody>
                <% @products.each do |product| %>
                  <tr>
                      <td class="col-sm-8 col-md-6">
                      <div class="media">
                          <a class="thumbnail pull-left" href="#"> <img class="media-object" src="http://icons.iconarchive.com/icons/custom-icon-design/flatastic-2/72/product-icon.png" style="width: 72px; height: 72px;"> </a>
                          <div class="media-body">
                              <h4 class="media-heading"><%= link_to product.name, "#" %></h4>
                              <span>Description: </span><span class="text-success"><strong><%=  product.description %></strong></span>
                              <br>
                              <span>Categories: </span><span ><strong><%=  product.added_categories %></strong></span>
                          </div>
                      </div></td>
                      <td class="col-sm-1 col-md-1 text-center"><strong><%=  product.price %></strong></td>
                      <td class="col-sm-1 col-md-1">
                        <%= link_to 'Edit', edit_vendors_product_path(product) %>
                        <%= link_to 'Show', vendors_product_path(product) %>
                        <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
                      </td>
                  </tr>
                <% end %>
              </tbody>
          </table>
      </div>
    </div>
</div>

app/views/vendors/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>
<br>
<%= link_to 'Back', vendors_products_path %>

app/views/vendors/products/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <p id="notice"><%= notice %></p>
      <div class="offer offer-default">
        <div class="shape">
          <div class="shape-text">
            Info
          </div>
        </div>
        <div class="offer-content">
          <h3 class="lead">
            <%= @product.name %>
          </h3>
          <p>
            <%= @product.description %>
            <br> and so one
          </p>
          <p><strong>Categories:</strong> <%= @product.added_categories %></p>
          <p><strong>Price:</strong> <%= @product.price %></p>
          <br>
          <p>
            <%= link_to 'Edit', edit_vendors_product_path(@product) %> |
            <%= link_to 'Back', vendors_products_path %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

<%= stylesheet_link_tag "vendors/products.css" %>