config/routes.rb
Ineed::Application.routes.draw do
  get "vendors/dashboard"
  get "users/dashboard"
  devise_for :users, :controllers => {:registrations => "users/registrations"}

  devise_scope :user do
    get "registrations/:role", to: "users/registrations#new", as: :registrations_by_role
  end

  match 'users/dashboard' => 'users#dashboard', :via => :get, :as => :user_dashboard
  match 'vendors/dashboard' => 'vendors#dashboard', :via => :get, :as => :vendor_dashboard
  get "home/index"

  namespace :vendors do
    resources :products
  end

  resources :products

  root 'home#index'
  ActiveAdmin.routes(self)

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
  <% unless name == :warning %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
    <% if name == :warning %>
      <div class="alert alert-warning">
        <a class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Demo Project", root_url, :class=>"navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home", root_path %></li>
        <li>
          <% if user_signed_in? %>
            <a href="<%= edit_user_registration_path %>"> <span class="glyphicon glyphicon-th"> Profile</span> </a>
          <% else %>
            <%= link_to('User Sign up', registrations_by_role_path("user")) %>
            <%= link_to('Vendor Sign up', registrations_by_role_path("vendor")) %>
          <% end %>
        </li>
        <% if current_user && current_user.admin? %>
          <li>
            <%= link_to 'Admin', admin_dashboard_path %>
          </li>
        <% end %>
        <li class="dropdown">
          <a href="." class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href=".">Action</a></li>
            <li><a href=".">Another action</a></li>
            <li><a href=".">Something else here</a></li>
            <li class="divider"></li>
            <li><a href=".">Separated link</a></li>
            <li class="divider"></li>
            <li><a href=".">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href=".">Link</a></li>
        <% if current_user %>
          <li class="dropdown">
            <a href="." class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href=".">Action</a></li>
              <li><a href=".">Another action</a></li>
              <li><a href=".">Something else here</a></li>
              <li class="divider"></li>
              <li>
                <% if user_signed_in? %>
               <a href="<%= destroy_user_session_path %>" data-method="delete" rel="nofollow"> <span class="glyphicon glyphicon-user"> Logout</span> </a>
            <% else %>
              <a href="<%= new_user_session_path %>"> <span class="glyphicon glyphicon-user"> Login</span> </a>
            <% end %>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <a href="<%= new_user_session_path %>"> <span class="glyphicon glyphicon-user"> Login</span> </a>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
<!--       <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button> -->
      <%= link_to "Ineed", root_url, :class=>"navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home", root_path %></li>
          <% if user_signed_in? %>
            <!-- <a href="<%#= edit_user_registration_path %>"> <span class="glyphicon glyphicon-th"> Profile</span> </a> -->
          <% else %>
          <li><%= link_to('User Sign up', registrations_by_role_path("user")) %></li>
          <li><%= link_to('Vendor Sign up', registrations_by_role_path("vendor")) %></li>
          <% end %>
        
        <% if current_user && current_user.vendor?  %>
          <li>
            <%= link_to 'My Products', vendors_products_path %>
          </li>
        <% end %>

        <% if current_user && current_user.admin? %>
          <li>
            <%= link_to 'Admin', admin_dashboard_path %>
          </li>
        <% end %>
          <li><%= link_to 'Products', products_path %></li>
        <!-- <li class="dropdown">
          <a href="." class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href=".">Action</a></li>
            <li><a href=".">Another action</a></li>
            <li><a href=".">Something else here</a></li>
            <li class="divider"></li>
            <li><a href=".">Separated link</a></li>
            <li class="divider"></li>
            <li><a href=".">One more separated link</a></li>
          </ul>
        </li> -->
      </ul>
      <% if user_signed_in? %>
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Ok</button>
        </form>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <!-- <li><a href=".">Link</a></li> -->
        <% if current_user %>
          <li class="dropdown">
            <a href="." class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href=".">Action</a></li>
              <li><a href=".">Another action</a></li>
              <li><a href=".">Something else here</a></li>
              <li class="divider"></li>
              <li>
                <% if user_signed_in? %>
               <a href="<%= destroy_user_session_path %>" data-method="delete" rel="nofollow"> <span class="glyphicon glyphicon-user"> Logout</span> </a>
            <% else %>
              <a href="<%= new_user_session_path %>"> <span class="glyphicon glyphicon-user"> Login</span> </a>
            <% end %>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <a href="<%= new_user_session_path %>"> <span class="glyphicon glyphicon-user"> Login</span> </a>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head lang="en">
  <title>Ineed</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render :partial => "layouts/navigation" %>
  <div class="container">
    <div class="row ext-messages">
      <div class="span8 offset2">
         <%= render 'layouts/messages' %>
      </div>
    </div>
    <div class="row-fluid">
      <div class="col-xs-12 col-md-12">
        <%= yield %>
      </div>
    </div>
  </div>
  <%= javascript_include_tag "misc" %>
</body>
</html>